[build]
builder = "nixpacks"

[build.nixpacks]
installCmd = "npm install"
buildCmd = "npx prisma generate"

[deploy]
startCommand = "node ${START_FILE}"
healthcheckPath = "${HEALTHCHECK_PATH}"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3